blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('',views.post_list,name='post_list'),
    path('<int:id>',views.post_detail,name='post_detail')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',namespace='blog'))
]

blog/models.py
from django.db import models
from django.db.models.query import QuerySet
from django.utils import timezone # เพิ่ม datetime
from django.contrib.auth.models import User # เพิ่มความสัมพันธ์กับ User


#crete model manager สำหรับ publich blog
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)

# Create your models here.
# สร้างโมเดล Post
class Post(models.Model):

    class Status(models.TextChoices): # เพิ่มฟิลด์ status
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
        
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now) # เพิ่ม datetime
    created = models.DateTimeField(auto_now_add=True) # เพิ่ม datetime
    updated = models.DateTimeField(auto_now=True) # เพิ่ม datetime
    status = models.CharField(max_length=2, 
                                choices=Status.choices, 
                                default=Status.DRAFT) # เพิ่มฟิลด์ status

    author = models.ForeignKey(User, 
                                on_delete=models.CASCADE, 
                                related_name='blog_posts') # เพิ่มความสัมพันธ์กับ User
    
    objects=models.Manager() #the dufault manager
    published=PublishedManager() #our custom manager

    class Meta: # การกำหนดการเรียงข้อมูลในโมเดล Post
        ordering = ['-publish'] # เรียงลำดับโพสต์จากวันที่ล่าสุดไปยังเก่าสุด
        indexes = [
            models.Index(fields=['-publish']), # เพิ่ม index
        ]

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
#import model
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.

#create func สำหรับอ่าน post ทั้งหมด
def post_list(request):
    #create ตัวแปรที่เก็บ post ทั้งหมดที่ publish
    posts=Post.published.all()

    #create ตัวแปรกำหนดจำนวน post ต่อ page
    per_page=1
    paginator=Paginator(posts,per_page)
    page=request.GET.get('page')
    try:
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts=paginator.page(paginator.num_pages)

    #ส่งค่า post ไปแสดง template 
    return render(request,'blog/post/list.html',{'posts':posts})

#create func to display POST detail
def post_detail(request,id):
    #create ตัวแปร post เก็บ id 
    post=Post.published.get(id=id)
    #ส่งค่า post ไปแสดง template 
    return render(request,'blog/post/detail.html',{'post':post})

blog/templates/blog/base.html
<!--Mater page-->

{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}{% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
          <div class="container">
            <a class="navbar-brand" href="{% url 'blog:post_list' %}">Blognull</a>
            <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavId">
                <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="#" aria-current="page">Home <span class="visually-hidden">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownId">
                            <a class="dropdown-item" href="#">Action 1</a>
                            <a class="dropdown-item" href="#">Action 2</a>
                        </div>
                    </li>
                </ul>
                <form class="d-flex my-2 my-lg-0">
                    <input class="form-control me-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
      </div>
    </nav>
    
    <div class="container">
        
        {% block content %}
            
        {% endblock %}
            
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %} #Call Master page

{% block title %} {{ post.title }} {% endblock %}
{% block content %}
    <div class="card mb-4">
        <div class="card-body">
            <h3>{{ post.title }}</h3>
            <small>{{ post.publish }} BY {{ post.author }}</small>
            <p class="mt-4">{{ post.body }}</p>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %} #Call Master page

{% block title %} My blog {% endblock %}
{% block content %}
    {% for post in posts %}
        <div class="card mb-4">
            <div class="card-header bg-primary text-white">
                <a href="{% url 'blog:post_detail' post.id %}" class="text-white text-decoration-none"><h5 class="card-title mb-4">{{ post.title }}</h5></a>
            </div>
            <div class="card-body">
                
                <p class="card-subtitle">{{ post.publish }} By {{ post.author }}</p>
                {{ post.body | truncatewords:30 | linebreaks }}
            </div>
        </div>
        
    {% endfor %}

    <nav aria-label="Page navigation">
      <ul class="pagination    ">
        
        {% if posts.has_previous %}
            <li class="page-item">
            <a class="page-link" href="?page={{ posts.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
            </li>
        {% endif %}
        {% for i in posts.paginator.page_range %}
            {% if posts.number == i %}
                <li class="page-item active"><a class="page-link" href="#">{{ posts.number }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if posts.has_next %}
            <li class="page-item">
            <a class="page-link" href="?page={{ posts.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
            </li>
        {% endif %}

      </ul>
    </nav>
{% endblock %}